routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('tracers', 'TracerController');
Route::resource('kuesioners', 'KuesionerController');
Route::post('regencies', 'KuesionerController@regencies')->name('regencies');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::put('/change_password/{id}', 'UserController@changePassword')->name('change_password');
    Route::get('/tracers-export', 'TracerController@export');
});

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fullname', 'email', 'password', 'username', 'gender', 'birthday', 'phone', 'picture', 'id_user_level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function user_level()
    {
        return $this->belongsTo(UserLevel::class, 'id_user_level');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\UserLevel;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Data User";
        $data['users'] = User::all();

        return view('back.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = "Tambah User";
        $data['user_levels'] = UserLevel::get();
        
        return view('back.users.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fullname' => 'required|max:255|regex:/^[\pL\s\-]+$/u',
            'username' => 'required|unique:users|max:20|min:6|alpha_dash',
            'password' => 'required|min:6',
            'confirm_password' => 'required|min:6|same:password',
            'email' => 'required|unique:users',
            'gender' => 'required',
            'id_user_level' => 'required',
            'phone' => 'required|unique:users|digits_between:9,16|numeric',
            'birthday' => 'nullable',
            'picture' => 'mimes:jpeg,bmp,png,jpg|max:2048'
        ]);

        $path = ($request->picture)
        ? $request->file('picture')->store("/public/input/users/profile")
        : null;

        $user = new User([
            'fullname' => $request->get('fullname'),
            'username' => $request->get('username'),
            'password' => Hash::make($request->get('password')),
            'email' => $request->get('email'),
            'gender' => $request->get('gender'),
            'phone' => $request->get('phone'),
            'birthday' => $request->get('birthday'),
            'id_user_level' => $request->get('id_user_level'),
            'picture' => $path
        ]);

        $user->save();
        return redirect('/users')->with('success', 'Pengguna berhasil ditambahkan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = "Edit User";
        $data['detail'] = User::findOrFail($id);
        $data['user_levels'] = UserLevel::get();

        return view('back.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'fullname' => 'required|max:255|regex:/^[\pL\s\-]+$/u',
            'username' => 'required|max:20|min:6|alpha_dash|unique:users,username,'.$id,
            'email' => 'required|unique:users,email,'.$id,
            'gender' => 'required',
            'id_user_level' => 'required',
            'phone' => 'required|digits_between:9,16|numeric|unique:users,phone,'.$id,
            'birthday' => 'nullable',
            'picture' => 'mimes:jpeg,bmp,png,jpg|max:2048'
        ]);
            
        $user = User::findOrFail($id);
        $path = ($request->picture)
        ? $request->file('picture')->store("/public/input/users/profile")
        : null;


        if ($request->picture) {
            Storage::delete($user->picture);
        }

        $user->fullname =  $request->get('fullname');
        $user->username = $request->get('username');
        $user->email = $request->get('email');
        $user->phone = $request->get('phone');
        $user->gender = $request->get('gender');
        $user->birthday = $request->get('birthday');
        $user->id_user_level = $request->get('id_user_level');
        if ($path != null) {
            $user->picture = $path;
        }
        $user->save();

        return redirect('/users')->with('success', 'Pengguna berhasil diperbaharui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if (Storage::exists($user->picture)) {
            Storage::delete($user->picture);
        }
        if ($user->delete()) {
            return redirect('/users')->with('success', 'Pengguna berhasil dihapus!');
        }else{
            return redirect('/users')->with('error', 'Pengguna gagal dihapus!');
        }
    }

    public function changePassword(Request $request, $id){

        $user = User::findOrFail($id);

        $request->validate([
            'new_password' => 'required|min:6',
            'confirm_password' => 'required|min:6|same:new_password'
        ]);

        if (!Hash::check($request->old_password, $user->password)) {
            return redirect(route('users.edit', $id))->with('error', 'Password lama anda salah!');
        }

        $user->password = Hash::make($request->new_password);

        if ($user->save()) {
            return redirect(route('users.edit', $id))->with('success', 'Password berhasil diperbaharui!');
        }else{
            return redirect(route('users.edit', $id))->with('error', 'Password gagal diperbaharui!');
        }

    }
}

resources/views/back/users/create.blade.php
@extends('layouts.back')
@section('js')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>
@endsection
@section('content')
<div class="content-page">
    <div class="content">
        
        <!-- Start Content-->
        <div class="container-fluid">
            <div class="row page-title">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb" class="float-right mt-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{url('users')}}">User</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Tambah</li>
                        </ol>
                    </nav>
                    <h4 class="mb-1 mt-0">Tambah</h4>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title mt-0 mb-1">Tambah User</h4>
                            <form class="needs-validation" action="{{route('users.store')}}" method="POST" enctype="multipart/form-data" novalidate>
                                @csrf
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">Nama Lengkap</label>
                                    <input type="text" class="form-control" name="fullname" id="validationCustom01" placeholder="Nama Lengkap" value="{{old('fullname') ?? null}}" required>
                                    @error('fullname')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustomUsername">Username</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                                        </div>
                                        <input type="text" class="form-control" id="validationCustomUsername" name="username" value="{{old('username') ?? null}}" placeholder="Username" aria-describedby="inputGroupPrepend"
                                            required>
                                        @error('username')
                                            <div class="invalid-feedback">
                                                {{$message}}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">Email</label>
                                    <input type="email" class="form-control" name="email" id="validationCustom01" placeholder="Email" value="{{old('email') ?? null}}" required>
                                    @error('email')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">Phone Number</label>
                                    <input type="number" class="form-control" name="phone" id="validationCustom01" placeholder="Phone Number" value="{{old('phone') ?? null}}">
                                    @error('phone')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">Jenis Kelamin</label>
                                    <div class="custom-control custom-radio mb-2">
                                        <input type="radio" value="Laki-laki" id="gender1" name="gender"
                                            class="custom-control-input">
                                        <label class="custom-control-label" for="gender1">Laki - laki</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input type="radio" value="Perempuan" id="gender2" name="gender"
                                            class="custom-control-input">
                                        <label class="custom-control-label" for="gender2">Perempuan</label>
                                    </div>
                                    @error('gender')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">Tanggal Lahir</label>
                                    <input type="date" class="form-control" name="birthday" id="validationCustom01" placeholder="Tanggal Lahir" value="{{old('birthday') ?? null}}">
                                    @error('birthday')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="validationCustom01">User Level</label>
                                    <select name="id_user_level" class="custom-select mb-2">
                                        @foreach ($user_levels as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                    @error('id_user_level')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label>Password</label>
                                    <div>
                                        <input type="password" class="form-control" name="password" id="validationCustom01" placeholder="Password" value="{{old('password') ?? null}}">
                                        @error('password')
                                            <div class="invalid-feedback">
                                                {{$message}}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="mt-2">
                                        <input type="password" class="form-control" name="confirm_password" id="validationCustom01" placeholder="Re-type Password" value="{{old('confirm_password') ?? null}}">
                                        @error('confirm_password')
                                            <div class="invalid-feedback">
                                                {{$message}}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group mb-3">
                                    <label class="mb-2">Profile Picture</label>
                                    <br>
                                    <img src="" id="profile-img-tag" width="200px" style="border-radius: 50%;object-fit:cover;" />
                                    <input type="file" class="form-control" name="picture" id="profile-img">
                                    @error('picture')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <button class="btn btn-primary" type="submit"> <i data-feather="user-plus" class="icon-xs"></i> Tambah User</button>
                            </form>

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>

        </div> <!-- container-fluid -->

    </div> <!-- content -->
@endsection

resources/views/back/users/edit.blade.php
@extends('layouts.back')
@section('js')
<script type="text/javascript">
    function readURL(input) {
        $('#profile-img-tag-current').hide();
        $('#profile-img-tag').show();
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>
@if (Session::get('success') || Session::get('error'))
<script>
    $('#ubahPassword').modal('show');
</script>
@endif
@error('new_password')
<script>
    $('#ubahPassword').modal('show');
</script>
@enderror
@error('confirm_password')
<script>
    $('#ubahPassword').modal('show');
</script>
@enderror
@endsection
@section('content')
<div class="content-page">
    <div class="content">
        
        <!-- Start Content-->
        <div class="container-fluid">
            <div class="row page-title">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb" class="float-right mt-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{url('users')}}">User</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        </ol>
                    </nav>
                    <h4 class="mb-1 mt-0">Edit</h4>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title mt-0 mb-1">Edit User</h4>
                            <div class="text-right">
                                <button type="button" class="btn btn-outline-warning btn-xs " data-toggle="modal" data-target="#ubahPassword">
                                    <i class="anticon anticon-key"></i> Ubah password ?
                                </button>
                            </div>
                            <form class="needs-validation" action="{{route('users.update', $detail->id)}}" method="POST" enctype="multipart/form-data" novalidate>
                                @csrf
                                @method('PUT')
                                <div class="form-group mb-3">
                                    <label for="">Nama Lengkap</label>
                                    <input type="text" class="form-control @error('fullname') is-invalid @enderror" name="fullname" id="" placeholder="Nama Lengkap" value="{{ $detail->fullname ?? old('fullname') }}" required>
                                    @error('fullname')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">Username</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                                        </div>
                                        <input type="text" class="form-control @error('username') is-invalid @enderror" id="" name="username" value="{{ $detail->username ?? old('username') }}" placeholder="Username" aria-describedby="inputGroupPrepend"
                                            required>
                                        @error('username')
                                            <div class="invalid-feedback">
                                                {{$message}}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">Email</label>
                                    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="" placeholder="Email" value="{{ $detail->email ?? old('email') }}" required>
                                    @error('email')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">Phone Number</label>
                                    <input type="number" class="form-control @error('phone') is-invalid @enderror" name="phone" id="" placeholder="Phone Number" value="{{ $detail->phone ?? old('phone') }}">
                                    @error('phone')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">Jenis Kelamin</label>
                                    <div class="custom-control custom-radio mb-2">
                                        <input type="radio" value="Laki-laki" id="gender1" name="gender"
                                            class="custom-control-input" {{($detail->gender == 'Laki-laki') ? 'checked' : null}}>
                                        <label class="custom-control-label" for="gender1">Laki - laki</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input type="radio" value="Perempuan" id="gender2" name="gender"
                                            class="custom-control-input" {{($detail->gender == 'Perempuan') ? 'checked' : null}}>
                                        <label class="custom-control-label" for="gender2">Perempuan</label>
                                    </div>
                                    @error('gender')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">Tanggal Lahir</label>
                                    <input type="date" class="form-control @error('username') is-invalid @enderror" name="birthday" id="" placeholder="Tanggal Lahir" value="{{ $detail->birthday ?? old('birthday') }}">
                                    @error('birthday')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label for="">User Level</label>
                                    <select name="id_user_level" class="custom-select mb-2">
                                        @foreach ($user_levels as $item)
                                            <option value="{{$item->id}}" {{($detail->id_user_level == $item->id) ? 'selected' : null}}>{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                    @error('id_user_level')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group mb-3">
                                    <label class="mb-2">Profile Picture</label>
                                    <br>
                                    @if ($detail->picture)
                                    <img src="{{Storage::url($detail->picture)}}" id="profile-img-tag-current"  width="200px" style="border-radius: 50%;object-fit:cover;" /><br>
                                    @endif
                                    <img src="" id="profile-img-tag" width="200px" style="border-radius: 50%;object-fit:cover;" />
                                    <input type="file" class="form-control @error('username') is-invalid @enderror" name="picture" id="profile-img">
                                    @error('picture')
                                        <div class="invalid-feedback">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <button class="btn btn-success" type="submit"> <i class="icon-xs" data-feather="save"></i> Simpan Perubahan</button>
                            </form>

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>

        </div> <!-- container-fluid -->

    </div> <!-- content -->
    <div class="modal fade" id="ubahPassword">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ubahPasswordTitle">Ubah Password</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="anticon anticon-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                        @if ($msg = Session::get('success'))
                                    <div class="alert alert-success">
                                        {{$msg}}
                                    </div>
                            @endif
                            @if ($msg = Session::get('error'))
                                    <div class="alert alert-danger">
                                        {{$msg}}
                                    </div>
                            @endif
                    <form action="{{route('change_password', $detail->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="col-md-12">
                        <label for="">Password Lama</label>
                        <input type="password" class="form-control m-b-15 @error('old_password') is-invalid @enderror" name="old_password"  placeholder="Password Lama">
                        @error('old_password')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                        <label for="">Password Baru</label>
                        <input type="password" class="form-control m-b-15 @error('new_password') is-invalid @enderror" name="new_password"  placeholder="Password Baru">
                        @error('new_password')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                        <label for="">Konfirmasi Password Baru</label>
                        <input type="password" class="form-control m-b-15 @error('confirm_password') is-invalid @enderror" name="confirm_password"  placeholder="Konfirmasi Password Baru">
                        @error('confirm_password')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Simpan perubahan</button>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection